export function previewHTML(artifact, saved, nonce) {
  const seed=JSON.stringify({id:artifact.id,nonce,data:saved?.data||{}}).replaceAll('<','\\u003c');
  // This document is served with its own CSP and placed in an opaque-origin iframe.
  return `<!doctype html><meta charset="UTF-8"><script>(()=>{const seed=${seed};let data=Object.assign(Object.create(null),seed.data);const send=(kind,extra={})=>parent.postMessage({workbenchPreview:true,artifactId:seed.id,nonce:seed.nonce,kind,...extra},'*');const save=()=>{if(JSON.stringify(data).length>100000)throw new DOMException('Storage quota exceeded','QuotaExceededError');send('storage',{data});};const storage={get length(){return Object.keys(data).length},key:i=>Object.keys(data)[i]??null,getItem:k=>Object.hasOwn(data,String(k))?data[String(k)]:null,setItem(k,v){k=String(k);v=String(v);const old=data[k],had=Object.hasOwn(data,k);data[k]=v;try{save();}catch(e){if(had)data[k]=old;else delete data[k];throw e;}},removeItem(k){delete data[String(k)];save();},clear(){data=Object.create(null);save();}};Object.defineProperty(window,'localStorage',{value:storage});window.addEventListener('error',e=>send('error',{message:String(e.message).slice(0,300)}));window.addEventListener('unhandledrejection',()=>send('error',{message:'发生未处理的异步错误'}));window.addEventListener('DOMContentLoaded',()=>send('loaded'));})();</script>${artifact.content}`;
}
export function standaloneHTML(artifact,saved){
  const seed=JSON.stringify({key:'co-work-export-'+artifact.id,data:saved?.data||{}}).replaceAll('<','\\u003c');
  return `<!doctype html><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"><script>(()=>{const seed=${seed};let data=Object.assign(Object.create(null),seed.data),native,warned=false;const warn=()=>{if(warned)return;warned=true;const show=()=>{const n=document.createElement('p');n.setAttribute('role','status');n.style.cssText='padding:12px;background:#fff0df;color:#703e22;font:14px sans-serif';n.textContent='当前浏览器未能保存操作数据。关闭前请保留备份，或返回共作工作区继续使用。';document.body.prepend(n)};document.readyState==='loading'?addEventListener('DOMContentLoaded',show,{once:true}):show();};try{native=window.localStorage;const saved=native.getItem(seed.key);if(saved){const parsed=JSON.parse(saved);if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))data=Object.assign(Object.create(null),parsed);}}catch{warn();}const persist=()=>{try{if(!native)throw Error();native.setItem(seed.key,JSON.stringify(data));}catch{warn();}};Object.defineProperty(window,'localStorage',{value:{get length(){return Object.keys(data).length},key:i=>Object.keys(data)[i]??null,getItem:k=>Object.hasOwn(data,String(k))?String(data[String(k)]):null,setItem(k,v){data[String(k)]=String(v);persist();},removeItem(k){delete data[String(k)];persist();},clear(){data=Object.create(null);persist();}}});})();</script>${artifact.content}`;
}
